# Generated by Django 2.0.13 on 2019-08-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=2083)),
                ('trailer_url', models.CharField(max_length=2083)),
                ('video_url', models.CharField(max_length=2083)),
                ('genre', models.CharField(max_length=127)),
                ('release_date', models.CharField(max_length=127)),
                ('director', models.CharField(max_length=255)),
                ('rating', models.SmallIntegerField()),
                ('country', models.CharField(max_length=127)),
                ('duration', models.SmallIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
