# Generated by Django 2.0.13 on 2019-08-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
