# Generated by Django 2.0.13 on 2019-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190823_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorsChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editors_movies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_movies', models.IntegerField()),
            ],
        ),
    ]
